<?php
namespace App\Thrift\HelloThrift;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Jeanku\Thrift\Base\TBase;
use Jeanku\Thrift\Type\TType;
use Jeanku\Thrift\Type\TMessageType;
use Jeanku\Thrift\Exception\TException;
use Jeanku\Thrift\Exception\TProtocolException;
use Jeanku\Thrift\Protocol\TProtocol;
use Jeanku\Thrift\Protocol\TBinaryProtocolAccelerated;
use Jeanku\Thrift\Exception\TApplicationException;



