<?php
namespace App\Thrift\HelloThrift;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use App\Util\lib\Base\TBase;
use App\Util\lib\Type\TType;
use App\Util\lib\Type\TMessageType;
use App\Util\lib\Exception\TException;
use App\Util\lib\Exception\TProtocolException;
use App\Util\lib\Protocol\TProtocol;
use App\Util\lib\Protocol\TBinaryProtocolAccelerated;
use App\Util\lib\Exception\TApplicationException;



